pipeline {
    agent any
    environment {
        RELEASE='1.0'
    }
    stages {
        stage('Build') {
            agent any
            environment {
                LOG_LEVEL='INFO'
            }
            steps {
                echo "Building release $(RLEASE) WITH build number $BUILD_NUMBER and log level $(LOG_LEVEL)..."
            }
        }
        stage('Test') {
            steps {
                echo "Testing. I can see ${RLEASE}, but not ${LOG_LEVEL}" 
            }
        }
    }
}