pipeline {
    agent any
    environment {
        RELEASE='1.0'   
    }
    stages {
        stage('Build') {
            environment {
                LOG_LEVEL='INFO'
            }
            steps {
                echo "Build Release ${RELEASE} with log level ${LOG_LEVEL}"
            }
        }
        stage('Test') {
            steps {
                echo "Testing. I can see ${RELEASE}" 
                writeFile file: 'test-results.txt', text: 'passed'
            }
        }
        
    }
    post {
        success {
            archiveArtifacts 'test-results.txt'
        }
    }
}